# Generated by Django 3.2.7 on 2021-09-30 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musics',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='music_id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 날짜')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 날짜')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='삭제 날짜')),
                ('singer', models.CharField(max_length=128, verbose_name='가수명')),
                ('title', models.CharField(max_length=128, verbose_name='곡명')),
                ('category', models.CharField(blank=True, choices=[('KPOP', '케이팝'), ('POP', '팝송'), ('CLASSIC', '클래식'), ('ETC', '기타 등등')], max_length=32, null=True, verbose_name='범주')),
                ('star_rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, '보통'), (2, '좋음'), (3, '매우 좋음')], default=1, null=True, verbose_name='곡 선호도')),
            ],
            options={
                'verbose_name_plural': '음악',
                'db_table': 'musics',
                'ordering': ['star_rating'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PlayList',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='playlist_id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 날짜')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='업데이트 날짜')),
                ('playlist_name', models.CharField(max_length=128, verbose_name='플레이리스트 이름')),
                ('music', models.ForeignKey(db_column='music_id', on_delete=django.db.models.deletion.CASCADE, related_name='music', to='api.musics', verbose_name='곡')),
            ],
            options={
                'verbose_name_plural': '플레이리스트',
                'db_table': 'playlist',
                'managed': True,
            },
        ),
    ]
